### ISSUE TITLE
Strange behavoir

### ISSUE THREAD

**Issue by jgalak** [khaytsus/direwolf-init#5]
I couldn't find any contact info for the author, so leaving this as an issue.  If you'd like to discuss it, feel free to email me at jgalak at gmail dot com

I am trying to use the scripts here to start direwolf.  This is being run on a RPi 3 using the latest release Raspbian.  

For testing, I modified direwolf.sh to comment out the PARENT_COMMAND test so as to be able to run the scripts from the command line, not from cron.

Running "sudo bash dw-start" the script returns to the command line with no output, and the following is shown in /tmp/dw-start.log (with a few extra echo statements as I was debugging):

----------------------- START
Tue May 29 13:28:26 EDT 2018
SDR == 1
Get Using SDR, so get newppm
Tue May 29 13:28:26 EDT 2018
----------------------- END
Running SDR
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Detached kernel driver
Found Rafael Micro R820T tuner
Tuner gain set to 49.60 dB.
Tuner error set to 170 ppm.
Tuned to 144643575 Hz.
Oversampling input by: 23x.
Oversampling output by: 1x.
Buffer size: 8.08ms
Exact sample rate is: 1014300.020041 Hz
Sampling at 1014300 S/s.
Output at 44100 Hz.
Signal caught, exiting!

User cancel, exiting...
Reattached kernel driver

Any idea why it appears to think it's been cancelled at the end there?

Thanks!

**Comment by khaytsus** [comment]
You might try echo'ing the command it's running and let me know what that is, and if it also errors if you run it manually.

I really need to clean this repo up and combine it with the other aprsobjects one; they're really two sides of the same coin.

**Comment by jgalak** [comment]
Aha!  Echoing the command eventually lead to an answer.  My bad.  I had direwolf.conf set up, but the program was looking for direwolf-sdr.conf

All good now.  Thanks for the help.

**Comment by khaytsus** [comment]
Aha, sometimes it's the darndest things ;)
